In [189]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline

In [190]:
df1=pd.read_csv('../input/wns2019contest/train.csv')
df2=pd.read_csv('../input/wns2019contest/view_log.csv')
df3=pd.read_csv('../input/wns2019contest/item_data.csv')

In [191]:
df= df1.merge(df2,how='inner',on='user_id')
df.head()

,impression_id,impression_time,user_id,app_code,os_version,is_4G,is_click,server_time,device_type,session_id,item_id
0,c4ca4238a0b923820dcc509a6f75849b,2018-11-15 00:00:00,87862,422,old,0,0,2018-10-19 18:11:00,android,190710,43886
1,621bf66ddb7c962aa0d22ac97d69b793,2018-11-15 00:19:00,87862,422,old,0,0,2018-10-19 18:11:00,android,190710,43886
2,ab394288aed46588bdc90bf4b541ec0d,2018-11-16 17:29:00,87862,422,old,0,0,2018-10-19 18:11:00,android,190710,43886
3,45c48cce2e2d7fbdea1afc51c7c6ad26,2018-11-15 00:01:00,63410,467,latest,1,1,2018-10-21 06:13:00,android,356854,43209
4,45c48cce2e2d7fbdea1afc51c7c6ad26,2018-11-15 00:01:00,63410,467,latest,1,1,2018-10-21 06:13:00,android,356854,66370

In [192]:
df.shape

(11052882, 11)

In [193]:
df.drop_duplicates(subset=['impression_time','user_id'],inplace=True)

In [194]:
df.shape

(237086, 11)

In [195]:
df_new=pd.merge(df,df3,how='inner',on='item_id')
df_new.shape

(236909, 16)

In [196]:
df_new.drop_duplicates(subset=['impression_time', 'item_id'], inplace=True)

In [197]:
df_new.shape

(235015, 16)

In [198]:
df_new.head()

,impression_id,impression_time,user_id,app_code,os_version,is_4G,is_click,server_time,device_type,session_id,item_id,item_price,category_1,category_2,category_3,product_type
0,c4ca4238a0b923820dcc509a6f75849b,2018-11-15 00:00:00,87862,422,old,0,0,2018-10-19 18:11:00,android,190710,43886,2350,11,35,20,5622
1,621bf66ddb7c962aa0d22ac97d69b793,2018-11-15 00:19:00,87862,422,old,0,0,2018-10-19 18:11:00,android,190710,43886,2350,11,35,20,5622
2,ab394288aed46588bdc90bf4b541ec0d,2018-11-16 17:29:00,87862,422,old,0,0,2018-10-19 18:11:00,android,190710,43886,2350,11,35,20,5622
3,45c48cce2e2d7fbdea1afc51c7c6ad26,2018-11-15 00:01:00,63410,467,latest,1,1,2018-10-21 06:13:00,android,356854,43209,3421,4,74,292,577
4,6b18886bc278247582704943f5c66eb9,2018-11-16 16:31:00,63410,467,latest,1,0,2018-10-21 06:13:00,android,356854,43209,3421,4,74,292,577

In [199]:
df_new['impression_time'] = pd.to_datetime(df_new['impression_time'])

In [200]:
df_new['impression_time']=pd.to_timedelta(df_new.impression_time).dt.total_seconds()

/opt/conda/lib/python3.6/site-packages/pandas/util/_decorators.py:208: FutureWarning: Passing datetime64-dtype data to TimedeltaIndex is deprecated, will raise a TypeError in a future version
  return func(*args, **kwargs)

In [201]:
df_new.head()

,impression_id,impression_time,user_id,app_code,os_version,is_4G,is_click,server_time,device_type,session_id,item_id,item_price,category_1,category_2,category_3,product_type
0,c4ca4238a0b923820dcc509a6f75849b,1.542240e+09,87862,422,old,0,0,2018-10-19 18:11:00,android,190710,43886,2350,11,35,20,5622
1,621bf66ddb7c962aa0d22ac97d69b793,1.542241e+09,87862,422,old,0,0,2018-10-19 18:11:00,android,190710,43886,2350,11,35,20,5622
2,ab394288aed46588bdc90bf4b541ec0d,1.542389e+09,87862,422,old,0,0,2018-10-19 18:11:00,android,190710,43886,2350,11,35,20,5622
3,45c48cce2e2d7fbdea1afc51c7c6ad26,1.542240e+09,63410,467,latest,1,1,2018-10-21 06:13:00,android,356854,43209,3421,4,74,292,577
4,6b18886bc278247582704943f5c66eb9,1.542386e+09,63410,467,latest,1,0,2018-10-21 06:13:00,android,356854,43209,3421,4,74,292,577

In [202]:
s=pd.get_dummies(df_new['os_version'])
df=pd.concat([df_new,s],axis=1)
df.drop(columns=['os_version'],inplace=True)

In [203]:
d=pd.get_dummies(df['device_type'])
df=pd.concat([df,d],axis=1)
df.drop(columns=['device_type'],inplace=True)

In [204]:
x=df.iloc[:,[1,3,4,8,9,10,11,12,13,14,15,16,17,18,19]].values
y=df.iloc[:,5].values

In [205]:
from sklearn.ensemble import RandomForestClassifier
classifier=RandomForestClassifier(n_estimators=100)
classifier.fit(x,y)
y.shape

(235015,)

In [206]:
# from keras.models import Sequential
# from keras.layers import Dense,LSTM,Dropout

# model=Sequential()
# model.add(LSTM(512,input_shape =(1, 15),return_sequences=True))
# model.add(Dropout(0.2))
# model.add(LSTM(512))
# model.add(Dropout(0.2))
# model.add(Dense(1,activation='sigmoid'))
# model.compile(loss='binary_crossentropy',optimizer='adam',metrics=['accuracy']) 
# model.fit(x.reshape([235015, 1, 15]),y,epochs=30,batch_size=128)  
# model.save('wns.h5')

In [207]:
df4=pd.read_csv('../input/wns2019contest/test.csv')
df4.shape
df4.head()

,impression_id,impression_time,user_id,app_code,os_version,is_4G
0,a9e7126a585a69a32bc7414e9d0c0ada,2018-12-13 07:44:00,44754,127,latest,1
1,caac14a5bf2ba283db7708bb34855760,2018-12-13 07:45:00,29656,44,latest,0
2,13f10ba306a19ce7bec2f3cae507b698,2018-12-13 07:46:00,25234,296,latest,1
3,39c4b4dc0e9701b55a0a4f072008fb3f,2018-12-13 07:47:00,22988,207,latest,1
4,bf5a572cca75f5fc67f4b14e58b11d70,2018-12-13 07:48:00,35431,242,latest,1

In [208]:
df_test= df4.merge(df2,how='inner',on='user_id')
df_test.head()

,impression_id,impression_time,user_id,app_code,os_version,is_4G,server_time,device_type,session_id,item_id
0,a9e7126a585a69a32bc7414e9d0c0ada,2018-12-13 07:44:00,44754,127,latest,1,2018-12-11 19:01:00,android,923045,128995
1,30e58abb328b85fd43398973f4daa190,2018-12-14 00:02:00,44754,127,latest,0,2018-12-11 19:01:00,android,923045,128995
2,9d43b6d8bc2e0cf1e0e67c0257f26497,2018-12-12 17:51:00,44754,127,latest,1,2018-12-11 19:01:00,android,923045,128995
3,3a6d8d6593becf63832bfc876768800f,2018-12-12 21:30:00,44754,127,latest,1,2018-12-11 19:01:00,android,923045,128995
4,0bef27d1e4eaac44e404f285dce6000b,2018-12-15 19:25:00,44754,127,latest,1,2018-12-11 19:01:00,android,923045,128995

In [209]:
df_test.drop_duplicates(subset=['impression_time','user_id'],inplace=True)
df_test.shape

(90373, 10)

In [210]:
df_test=pd.merge(df_test,df3,how='inner',on='item_id')
df_test.shape

(90294, 15)

In [211]:
df_test.drop_duplicates(subset=['impression_time', 'item_id'], inplace=True)
df_test.shape

(89228, 15)

In [212]:
df_test['impression_time'] = pd.to_datetime(df_test['impression_time'])
df_test['impression_time']=pd.to_timedelta(df_test.impression_time).dt.total_seconds()

/opt/conda/lib/python3.6/site-packages/pandas/util/_decorators.py:208: FutureWarning: Passing datetime64-dtype data to TimedeltaIndex is deprecated, will raise a TypeError in a future version
  return func(*args, **kwargs)

In [213]:
s=pd.get_dummies(df_test['os_version'])
df_pred=pd.concat([df_test,s],axis=1)
df_pred.drop(columns=['os_version'],inplace=True)

In [214]:
d=pd.get_dummies(df_pred['device_type'])
df_pred=pd.concat([df_pred,d],axis=1)
df_pred.drop(columns=['device_type'],inplace=True)

In [215]:
df_pred.head()

,impression_id,impression_time,user_id,app_code,is_4G,server_time,session_id,item_id,item_price,category_1,category_2,category_3,product_type,intermediate,latest,old,android,iphone,web
0,a9e7126a585a69a32bc7414e9d0c0ada,1.544687e+09,44754,127,1,2018-12-11 19:01:00,923045,128995,23424,1,42,220,1617,0,1,0,1,0,0
1,30e58abb328b85fd43398973f4daa190,1.544746e+09,44754,127,0,2018-12-11 19:01:00,923045,128995,23424,1,42,220,1617,0,1,0,1,0,0
2,9d43b6d8bc2e0cf1e0e67c0257f26497,1.544637e+09,44754,127,1,2018-12-11 19:01:00,923045,128995,23424,1,42,220,1617,0,1,0,1,0,0
3,3a6d8d6593becf63832bfc876768800f,1.544650e+09,44754,127,1,2018-12-11 19:01:00,923045,128995,23424,1,42,220,1617,0,1,0,1,0,0
4,0bef27d1e4eaac44e404f285dce6000b,1.544902e+09,44754,127,1,2018-12-11 19:01:00,923045,128995,23424,1,42,220,1617,0,1,0,1,0,0

In [216]:
x_test=df_pred.iloc[:,[1,3,4,7,8,9,10,11,12,13,14,15,16,17,18]].values

In [217]:
y_pred=classifier.predict(x_test)

In [218]:
y_pred.shape

(89228,)

In [219]:
unique_values,counts = np.unique(y_pred,return_counts=True)

In [220]:
unique_values

array([0, 1])

In [221]:
counts

array([87955,  1273])

In [222]:
df_pred["prediction"] = classifier.predict(x_test)

In [223]:
df_pred.head()

,impression_id,impression_time,user_id,app_code,is_4G,server_time,session_id,item_id,item_price,category_1,category_2,category_3,product_type,intermediate,latest,old,android,iphone,web,prediction
0,a9e7126a585a69a32bc7414e9d0c0ada,1.544687e+09,44754,127,1,2018-12-11 19:01:00,923045,128995,23424,1,42,220,1617,0,1,0,1,0,0,0
1,30e58abb328b85fd43398973f4daa190,1.544746e+09,44754,127,0,2018-12-11 19:01:00,923045,128995,23424,1,42,220,1617,0,1,0,1,0,0,0
2,9d43b6d8bc2e0cf1e0e67c0257f26497,1.544637e+09,44754,127,1,2018-12-11 19:01:00,923045,128995,23424,1,42,220,1617,0,1,0,1,0,0,0
3,3a6d8d6593becf63832bfc876768800f,1.544650e+09,44754,127,1,2018-12-11 19:01:00,923045,128995,23424,1,42,220,1617,0,1,0,1,0,0,0
4,0bef27d1e4eaac44e404f285dce6000b,1.544902e+09,44754,127,1,2018-12-11 19:01:00,923045,128995,23424,1,42,220,1617,0,1,0,1,0,0,0

In [224]:
df_pred.sort_values('impression_time')

,impression_id,impression_time,user_id,app_code,is_4G,server_time,session_id,item_id,item_price,category_1,category_2,category_3,product_type,intermediate,latest,old,android,iphone,web,prediction
72118,ee0a836f8620592791fe33a629eb8d17,1.544573e+09,72729,129,0,2018-12-07 08:42:00,120672,50870,10078,9,3,27,6455,1,0,0,1,0,0,0
2358,a262ad869b347553956e2f460362d837,1.544573e+09,32684,7,0,2018-11-21 02:40:00,225049,1528,7320,9,44,114,3528,0,1,0,1,0,0,0
64409,4d1534b976ee10cbb1390f9d3adb3646,1.544573e+09,1838,470,1,2018-11-16 07:25:00,9030,106866,416,7,24,100,2356,1,0,0,1,0,0,0
7010,c56bbd96f9056f3aefd9fe2a3b75f813,1.544573e+09,31257,207,1,2018-10-15 21:32:00,574039,93170,20428,9,9,90,5432,0,1,0,1,0,0,0
21430,baf48d04f9e742bc9b300291caafe986,1.544573e+09,81444,207,0,2018-10-25 20:21:00,400843,32155,3187,9,9,244,10412,1,0,0,1,0,0,0
38630,ec987c053cfa0291a19c6359d3aa9d26,1.544573e+09,24970,129,0,2018-10-19 20:04:00,483354,11479,13708,8,40,84,5036,1,0,0,1,0,0,0
8966,13ddfbf7bd5fc64405dc406fe3048fda,1.544573e+09,57697,190,0,2018-11-17 20:43:00,734898,91875,140800,9,3,27,6878,0,1,0,1,0,0,0
43651,3f964522e5a8a051b04fa97f145e0d55,1.544573e+09,75720,390,1,2018-10-28 23:27:00,934656,58337,5702,11,35,20,5662,1,0,0,1,0,0,0
35254,e086939a755a2153d8ace7f3f09fc12e,1.544573e+09,47936,207,0,2018-10-28 14:42:00,1026249,30048,2496,10,43,264,5386,0,0,1,1,0,0,0
15612,e8f646901d982b43f05ea18cfe240b90,1.544573e+09,13175,127,0,2018-10-25 22:13:00,118431,425,1025,4,74,292,4524,1,0,0,1,0,0,0
16262,44b3d601e0c4c9e3751fed77058051e0,1.544573e+09,88814,318,1,2018-10-18 23:42:00,807368,104487,7478,17,39,252,2874,1,0,0,1,0,0,0
4268,26b938e2963d76acda599ac3ff67791e,1.544573e+09,32143,151,1,2018-12-09 21:20:00,985341,57465,1152,1,36,203,2270,0,1,0,1,0,0,0
72983,7b5519800845726817702077d593c74e,1.544573e+09,21784,190,1,2018-10-15 13:37:00,354351,37207,768,15,47,261,8655,0,1,0,1,0,0,0
34916,76c62d3e9ee6eae18da14d183ee8c9be,1.544573e+09,63471,190,0,2018-11-20 20:21:00,735727,80771,11697,9,3,48,6347,1,0,0,1,0,0,0
57711,0f38ed608aa2a3b775698be035038b90,1.544573e+09,58470,190,1,2018-11-05 10:06:00,95625,48747,109670,9,3,172,2099,0,0,1,1,0,0,0
33577,5da7e26ef8cd41ff378989e8d7542349,1.544573e+09,15876,37,0,2018-11-13 20:40:00,209907,17268,4352,4,38,62,4911,0,1,0,1,0,0,0
34158,65fa6785db57aeded5cf37c657cb48cc,1.544573e+09,25422,190,0,2018-10-28 10:12:00,167207,64835,8960,11,76,147,7455,1,0,0,1,0,0,0
77534,8e075b4e231aa8503a2c0433524786f8,1.544573e+09,43586,244,0,2018-10-22 22:27:00,428325,14273,1081,17,55,58,1606,0,0,1,1,0,0,0
37282,664a0ed28a2e2f2f61455d444732c640,1.544573e+09,37550,190,0,2018-10-17 15:40:00,580789,85162,737,4,74,292,4524,1,0,0,1,0,0,0
79867,eab2630405b987849c4ef00fa9df7704,1.544573e+09,32042,385,1,2018-11-27 15:41:00,271509,79819,819,0,6,145,6116,1,0,0,1,0,0,0
4754,3c2e477337d0c2e35e907797b32079d6,1.544573e+09,12353,190,0,2018-10-16 00:22:00,92313,84085,14656,1,64,263,2417,0,0,1,1,0,0,0
81069,dca8e47c4438b24e2b719ffa2cefe7e9,1.544573e+09,18895,190,1,2018-10-16 12:20:00,673549,64546,12736,1,64,263,5164,0,1,0,1,0,0,0
23841,4af326e60992a1a0b6e0804ca8553046,1.544573e+09,32124,207,1,2018-10-27 08:40:00,489824,108274,3264,1,64,263,576,0,0,1,1,0,0,0
24717,6033f1aa0458ec11a0609bd20a326b79,1.544573e+09,12053,371,0,2018-11-07 19:09:00,576547,78603,24640,1,36,203,8584,0,1,0,1,0,0,0
20961,12e1e357f22c8a419e9c047b38159a77,1.544573e+09,73490,190,0,2018-10-23 20:18:00,416035,21137,8896,1,7,246,2475,0,1,0,1,0,0,0
47697,b39af2147def295cbaadd8f65a638eeb,1.544573e+09,44645,244,0,2018-10-28 09:14:00,521186,51113,1024,10,43,264,6641,0,1,0,1,0,0,0
5143,2b41b102f11f31caf402087209bd4d00,1.544573e+09,54589,244,1,2018-10-15 23:27:00,723861,84704,3833,10,63,220,5251,0,1,0,1,0,0,0
24778,4b152c261aab68ef49e1dee389e3236e,1.544573e+09,36663,217,1,2018-10-16 22:43:00,793655,78603,24640,1,36,203,8584,0,1,0,1,0,0,0
33102,7e957b29c0efe65247545466a3d4f290,1.544573e+09,81627,318,1,2018-12-11 13:23:00,114851,99981,1504,6,73,249,5798,0,1,0,1,0,0,0
71736,79e69e5e08008b2e30c9cf6e655ac2f8,1.544573e+09,3614,190,0,2018-11-17 10:37:00,296381,87888,2937,17,39,151,251,0,0,1,1,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
90219,d71af99f4287f58bff7101f57947e1d2,1.545177e+09,48187,386,0,2018-10-23 12:45:00,520456,70653,1946,7,23,149,7203,0,1,0,1,0,0,0
57585,d004a2ed6794f69ce3376cbcd87f8dce,1.545177e+09,73008,202,0,2018-10-18 13:08:00,623970,76640,1734,14,62,317,9514,0,1,0,1,0,0,0
38946,07221edb6c129c914a49343fc782a2bb,1.545177e+09,92463,409,0,2018-11-12 10:37:00,1012405,110337,737,14,61,132,6361,0,0,1,1,0,0,0
12240,aebc5d53c28b259a9ef579a80e84306c,1.545177e+09,77521,469,0,2018-10-23 21:48:00,334571,79527,6336,4,38,62,3928,1,0,0,1,0,0,0
8908,14e40cf9f6b71d972a8cbf6836a230c4,1.545177e+09,69289,371,0,2018-11-03 16:01:00,112526,117580,10816,10,63,220,12,0,1,0,1,0,0,0
45011,87b64ee438df27db0b5b9a573de1eb71,1.545177e+09,49232,190,1,2018-11-19 21:40:00,105259,11986,2873,13,52,275,4833,0,1,0,1,0,0,0
2000,9b134c6b789846d25577969461ccaace,1.545177e+09,12688,244,1,2018-10-17 18:41:00,706226,1528,7320,9,44,114,3528,1,0,0,1,0,0,0
40132,93ebd7f1e2734d8f44b056fef06bcdde,1.545177e+09,31702,463,1,2018-10-17 13:45:00,1053992,75607,54144,9,3,27,2099,0,0,1,1,0,0,0
55365,c49c387fb14ed07d9746fc4cee06664d,1.545177e+09,58859,9,0,2018-10-19 23:40:00,657238,127117,20672,1,64,263,1783,0,0,1,1,0,0,0
16089,0d1dec36b2d1f685e738834f7d785f1d,1.545177e+09,38318,514,0,2018-11-02 07:42:00,525954,4035,24256,1,42,157,2844,0,1,0,1,0,0,0
41200,24b39bd3eff16511e88812d559958b28,1.545177e+09,65814,202,0,2018-12-04 13:08:00,598580,92576,3853,17,69,154,257,0,1,0,1,0,0,0
52040,e473cad398d5de9cb5be83d9a9ca0b97,1.545177e+09,28539,151,1,2018-10-19 15:53:00,104851,89373,2496,17,8,113,10025,0,1,0,1,0,0,0
8907,4ba4b2e30d3b3b7d54caeaf79f81eb52,1.545177e+09,69289,371,0,2018-11-03 16:01:00,112526,117580,10816,10,63,220,12,0,1,0,1,0,0,0
65592,c60cda6251b09f170253c3d624e90401,1.545177e+09,66401,44,0,2018-10-15 15:58:00,546972,52723,1081,10,63,303,3055,0,0,1,1,0,0,0
27155,53d66b0823f923a1e38cb2d37a3d9648,1.545177e+09,82495,213,0,2018-11-05 06:38:00,565571,82387,1548,14,61,132,8600,0,1,0,1,0,0,0
70683,bb662950d43225a85f02dab455ff656c,1.545177e+09,57079,386,0,2018-12-06 20:50:00,591553,103097,21696,1,64,263,5164,0,1,0,1,0,0,0
70711,e9ee81b285b16321eb13f7fea71babd6,1.545177e+09,39769,44,0,2018-10-15 13:51:00,227068,115805,6368,7,24,51,7577,1,0,0,1,0,0,0
90064,68b52818fecf4a611688967b586e01c5,1.545177e+09,26345,207,0,2018-10-16 00:51:00,966233,70148,38432,1,42,157,6239,1,0,0,1,0,0,0
22941,e99817afa73431282bb3ddb6eaff1ff7,1.545177e+09,54764,243,0,2018-10-17 17:08:00,460258,1525,2553,16,56,93,8986,0,0,1,1,0,0,0
20586,d9fd5ff88078d719a9996014194e6ad2,1.545177e+09,39725,207,0,2018-10-21 17:35:00,597035,72633,23485,9,44,114,8324,0,1,0,1,0,0,0
90065,fe5e8faf59c8061f7befa3dbca2ace00,1.545177e+09,80894,129,1,2018-12-11 10:54:00,108326,24149,3712,10,63,295,9959,0,1,0,1,0,0,0
55940,cd14139956e6ef64ab3aa6cb6549645a,1.545177e+09,13550,3,0,2018-10-19 11:24:00,758875,129770,4467,9,44,114,2645,0,1,0,1,0,0,0
56237,46d2b63d04b702b10dba9aea66922182,1.545178e+09,75373,296,0,2018-10-18 17:31:00,39633,109516,12609,16,20,269,6564,1,0,0,1,0,0,0
42914,70ace7a2908312f7e24a427afefb2a55,1.545178e+09,22313,272,1,2018-10-15 19:07:00,27786,109289,4025,16,56,42,7962,0,1,0,1,0,0,0
38947,16b172d83d6979204bfa35df45aee98f,1.545178e+09,92463,409,0,2018-11-12 10:37:00,1012405,110337,737,14,61,132,6361,0,0,1,1,0,0,0
61412,7cfb048dd90b05f0a3ec8467d1074dbd,1.545178e+09,3547,129,1,2018-12-07 17:04:00,722462,73745,2553,10,43,187,7701,0,1,0,1,0,0,0
65440,539145030fb3600d26d6a64130310035,1.545178e+09,82078,242,1,2018-11-30 11:28:00,580845,66430,61190,1,42,157,5208,0,1,0,1,0,0,1
81639,18888f049bc764e9a84466163cc9f9f3,1.545178e+09,56499,190,0,2018-12-10 09:20:00,191782,125578,896,11,51,15,4432,1,0,0,1,0,0,0
17817,90c5d65e00cf3a66d809250f1fcc75fa,1.545178e+09,29427,372,1,2018-12-01 20:25:00,376259,72955,2344,0,6,145,2056,0,1,0,1,0,0,0
90218,8acb40e83c94e3889047bc1cb4d6b39d,1.545178e+09,48187,386,0,2018-10-23 12:45:00,520456,70653,1946,7,23,149,7203,0,1,0,1,0,0,0

In [225]:
import time
df_pred['impression_time'] = df_pred['impression_time'].apply(lambda x: time.strftime('%Y-%m-%d %H:%M:%S', time.gmtime(x)))

In [226]:
df_pred.head()

,impression_id,impression_time,user_id,app_code,is_4G,server_time,session_id,item_id,item_price,category_1,category_2,category_3,product_type,intermediate,latest,old,android,iphone,web,prediction
0,a9e7126a585a69a32bc7414e9d0c0ada,2018-12-13 07:44:00,44754,127,1,2018-12-11 19:01:00,923045,128995,23424,1,42,220,1617,0,1,0,1,0,0,0
1,30e58abb328b85fd43398973f4daa190,2018-12-14 00:02:00,44754,127,0,2018-12-11 19:01:00,923045,128995,23424,1,42,220,1617,0,1,0,1,0,0,0
2,9d43b6d8bc2e0cf1e0e67c0257f26497,2018-12-12 17:51:00,44754,127,1,2018-12-11 19:01:00,923045,128995,23424,1,42,220,1617,0,1,0,1,0,0,0
3,3a6d8d6593becf63832bfc876768800f,2018-12-12 21:30:00,44754,127,1,2018-12-11 19:01:00,923045,128995,23424,1,42,220,1617,0,1,0,1,0,0,0
4,0bef27d1e4eaac44e404f285dce6000b,2018-12-15 19:25:00,44754,127,1,2018-12-11 19:01:00,923045,128995,23424,1,42,220,1617,0,1,0,1,0,0,0

In [227]:
df_pred = df_pred.sort_values(['impression_time'])

In [228]:
df_pred.shape

(89228, 20)

In [229]:
df_pred.head()

,impression_id,impression_time,user_id,app_code,is_4G,server_time,session_id,item_id,item_price,category_1,category_2,category_3,product_type,intermediate,latest,old,android,iphone,web,prediction
72118,ee0a836f8620592791fe33a629eb8d17,2018-12-12 00:00:00,72729,129,0,2018-12-07 08:42:00,120672,50870,10078,9,3,27,6455,1,0,0,1,0,0,0
2358,a262ad869b347553956e2f460362d837,2018-12-12 00:00:00,32684,7,0,2018-11-21 02:40:00,225049,1528,7320,9,44,114,3528,0,1,0,1,0,0,0
64409,4d1534b976ee10cbb1390f9d3adb3646,2018-12-12 00:00:00,1838,470,1,2018-11-16 07:25:00,9030,106866,416,7,24,100,2356,1,0,0,1,0,0,0
7010,c56bbd96f9056f3aefd9fe2a3b75f813,2018-12-12 00:00:00,31257,207,1,2018-10-15 21:32:00,574039,93170,20428,9,9,90,5432,0,1,0,1,0,0,0
21430,baf48d04f9e742bc9b300291caafe986,2018-12-12 00:00:00,81444,207,0,2018-10-25 20:21:00,400843,32155,3187,9,9,244,10412,1,0,0,1,0,0,0

In [230]:
#  if(df_pred[['impression_time','user_id']] is df4[['impression_time','user_id']]):
#         df4['is_click'] ='f'
#  else:
#     df4['is_click']='u'
        
# df4.head()

,impression_id,impression_time,user_id,app_code,os_version,is_4G,is_click
0,a9e7126a585a69a32bc7414e9d0c0ada,2018-12-13 07:44:00,44754,127,latest,1,u
1,caac14a5bf2ba283db7708bb34855760,2018-12-13 07:45:00,29656,44,latest,0,u
2,13f10ba306a19ce7bec2f3cae507b698,2018-12-13 07:46:00,25234,296,latest,1,u
3,39c4b4dc0e9701b55a0a4f072008fb3f,2018-12-13 07:47:00,22988,207,latest,1,u
4,bf5a572cca75f5fc67f4b14e58b11d70,2018-12-13 07:48:00,35431,242,latest,1,u

In [231]:
# df4['is_click']=[if(df_pred.impression_time is df4.impression_time and df_pred.user_id is df4.user_id)]

In [232]:
# df4['is_click'] = np.where(df_pred.impression_time.values == df4.impression_time.values and df_pred.user_id == df4.user_id , df_pred['prediction'], 'False')

/opt/conda/lib/python3.6/site-packages/ipykernel_launcher.py:1: DeprecationWarning: elementwise comparison failed; this will raise an error in the future.
  """Entry point for launching an IPython kernel.

ValueError: Length of values does not match length of index

In [ ]:
# df4.head()

In [ ]:
df_pred.head()

In [ ]:
pred=df_pred[['impression_time','prediction']]

In [ ]:
pred.to_csv('submit.csv')

In [233]:
dfnew=pd.read_csv('submit.csv')

In [234]:
dfnew.reset_index()

       index  Unnamed: 0                     impression_id  prediction
0          0       72118  ee0a836f8620592791fe33a629eb8d17           0
1          1        2358  a262ad869b347553956e2f460362d837           0
2          2       64409  4d1534b976ee10cbb1390f9d3adb3646           0
3          3        7010  c56bbd96f9056f3aefd9fe2a3b75f813           0
4          4       21430  baf48d04f9e742bc9b300291caafe986           0
...      ...         ...                               ...         ...
89223  89223       61412  7cfb048dd90b05f0a3ec8467d1074dbd           0
89224  89224       65440  539145030fb3600d26d6a64130310035           1
89225  89225       81639  18888f049bc764e9a84466163cc9f9f3           0
89226  89226       17817  90c5d65e00cf3a66d809250f1fcc75fa           0
89227  89227       90218  8acb40e83c94e3889047bc1cb4d6b39d           0

[89228 rows x 4 columns]